/usr/lib/python3/dist-packages/gpg*.egg-info
/usr/lib/python3/dist-packages/gpg/*py
/usr/lib/python3/dist-packages/gpg/_gpgme*.so
/usr/lib/python3/dist-packages/gpg/constants/*.py
/usr/lib/python3/dist-packages/gpg/constants/data/*.py
/usr/lib/python3/dist-packages/gpg/constants/keylist/*.py
/usr/lib/python3/dist-packages/gpg/constants/sig/*.py
/usr/lib/python3/dist-packages/gpg/constants/tofu/*.py
